In [1]:
import numpy as np
from numpy import random

In [2]:
def bisigmoid(x):
    return (1-np.exp(-x))/(1+np.exp(-x))


In [3]:
def fdNet(r):
    return (1-r**2)/2

In [4]:
c=1
training_inputs=np.array([[1,0,0,-1],[0,1,0,-1],[-1,1,0,-1]])
print("Training inputs are\n ",training_inputs)

Training inputs are
  [[ 1  0  0 -1]
 [ 0  1  0 -1]
 [-1  1  0 -1]]


In [5]:
init_weights=random.rand(4)
print("initial weights are\n ",init_weights)

initial weights are
  [0.05961864 0.53870686 0.21545413 0.48259734]


In [6]:
d=np.array([-1,0,1])

In [7]:
for z in range(900):
    print("iteration:",z+1)
    j=0;
    for i in training_inputs:
        fnet=bisigmoid(np.dot(i,init_weights.T))
        fdnet=fdNet(fnet)
        temp=c*(d[j]-fnet)*fdnet
        del_w=np.dot(i,temp)
        init_weights+=del_w
        j=j+1
        print("Updated Weights:\n",init_weights)
    print("\n")

iteration: 1
Updated Weights:
 [-0.31899694  0.53870686  0.21545413  0.86121292]
Updated Weights:
 [-0.31899694  0.61659874  0.21545413  0.78332105]
Updated Weights:
 [-0.7783338   1.07593559  0.21545413  0.32398419]


iteration: 2
Updated Weights:
 [-0.96496656  1.07593559  0.21545413  0.51061695]
Updated Weights:
 [-0.96496656  0.94869316  0.21545413  0.63785938]
Updated Weights:
 [-1.11393388  1.09766048  0.21545413  0.48889207]


iteration: 3
Updated Weights:
 [-1.20744851  1.09766048  0.21545413  0.58240671]
Updated Weights:
 [-1.20744851  0.97963181  0.21545413  0.70043537]
Updated Weights:
 [-1.31840865  1.09059195  0.21545413  0.58947524]


iteration: 4
Updated Weights:
 [-1.3765681   1.09059195  0.21545413  0.64763469]
Updated Weights:
 [-1.3765681   0.98680339  0.21545413  0.75142324]
Updated Weights:
 [-1.46881256  1.07904786  0.21545413  0.65917877]


iteration: 5
Updated Weights:
 [-1.50928238  1.07904786  0.21545413  0.69964858]
Updated Weights:
 [-1.50928238  0.98861326 

In [8]:
#TEST
x1=np.array([1,0,0,0])

In [9]:
#TEST
Y1=bisigmoid(np.dot(x1,init_weights.T))
print(Y1)
#EXPECTED VALUE -1

-0.9771775565734678
