In [1]:
import numpy as np

In [2]:
def signum(x):
    if(x<0):
        return -1
    else:
        return 1

In [3]:
c=1
training_input=np.array([[-1,2,1.5,0],[1,-0.5,-2,-1.5],[0,1,-1,1.5]])
print("training inputs are:\n",training_input)

training inputs are:
 [[-1.   2.   1.5  0. ]
 [ 1.  -0.5 -2.  -1.5]
 [ 0.   1.  -1.   1.5]]


In [4]:
init_weights=np.array([1,-1,0,0.5])
print("Weights are:\n",init_weights)

Weights are:
 [ 1.  -1.   0.   0.5]


In [5]:
for z in range(3):
    print("iteration",z+1)
    for i in training_input:
        fnet=signum(np.dot(i,init_weights.T))
        def_w=np.dot(i,fnet)
        init_weights+=def_w;
        print("updated weights are:",init_weights)
    print("\n")

iteration 1
updated weights are: [ 2.  -3.  -1.5  0.5]
updated weights are: [ 3.  -3.5 -3.5 -1. ]
updated weights are: [ 3.  -4.5 -2.5 -2.5]


iteration 2
updated weights are: [ 4.  -6.5 -4.  -2.5]
updated weights are: [ 5. -7. -6. -4.]
updated weights are: [ 5.  -8.  -5.  -5.5]


iteration 3
updated weights are: [  6.  -10.   -6.5  -5.5]
updated weights are: [  7.  -10.5  -8.5  -7. ]
updated weights are: [  7.  -11.5  -7.5  -8.5]


