In [7]:
import numpy as np
from numpy import random

In [8]:
c=0.5
training_inputs=np.array([[2,0,1],[2,-2,1],[1,-2,-1]])
print("Training Inputs:\n",training_inputs)

Training Inputs:
 [[ 2  0  1]
 [ 2 -2  1]
 [ 1 -2 -1]]


In [9]:
init_weights=random.rand(3)
print("Inititial Weights are:\n",init_weights)

Inititial Weights are:
 [0.58002461 0.70916813 0.44302716]


In [10]:
d=np.array([1,0,1])
print("D are:\n",d)

D are:
 [1 0 1]


In [11]:
for z in range(500):
    print("iterations:",z+1)
    j=0;
    for i in training_inputs:
        net=np.dot(i,init_weights.T)
        temp=c*(d[j]-net)
        del_w=np.dot(i,temp)
        init_weights+=del_w
        j=j+1
        print("Updated Weights are:",init_weights)
    print("\n")
    

iterations: 1
Updated Weights are: [-0.02305177  0.70916813  0.14148897]
Updated Weights are: [ 1.29989905 -0.61378269  0.80296438]
Updated Weights are: [0.93764902 0.11071736 1.16521441]


iterations: 2
Updated Weights are: [-1.10286343  0.11071736  0.14495818]
Updated Weights are: [ 1.17933997 -2.17148604  1.28605988]
Updated Weights are: [-0.43878612  1.06476613  2.90418596]


iterations: 3
Updated Weights are: [-1.46539985  1.06476613  2.3908791 ]
Updated Weights are: [ 1.20405301 -1.60468673  3.72560552]
Updated Weights are: [ 1.36014254 -1.91686579  3.56951599]


iterations: 4
Updated Weights are: [-3.92965853 -1.91686579  0.92461546]
Updated Weights are: [-0.82868851 -5.01783581  2.47510047]
Updated Weights are: [-3.69462983  0.71404683  5.34104179]


iterations: 5
Updated Weights are: [-0.64641195  0.71404683  6.86515073]
Updated Weights are: [-4.79064511  4.85827999  4.79303415]
Updated Weights are: [  5.35947451 -15.44195924  -5.35708547]


iterations: 6
Updated Weights are: 

In [12]:
#TEST
x1=np.array([1,0,0])
print(np.dot(x1,init_weights.T))
#EXPECTED VALUE 1

4.453952395500756e+227
